### ISSUE TITLE
Unable to pull llama 3 after following the process 

### ISSUE THREAD

**Issue by Nishantg7** [brknsoul/ROCmLibs#3]
I followed all the steps mentioned and could not pull llama3 or any other models. It works on my CPU but when I configured it with GPU as per the guide, it could not pull any model and there were no network issues.
The error that I was getting was "error: max retries exceeded", Is there any other alternative I can try that might work?

OS: WINDOWS 10
GPU: RX6600
RAM: 16 GB

**Comment by brknsoul** [comment]
ROCmLibs isn't a place for troubleshooting issues with anything. It's only a repository for ROCm Libraries.

**Comment by Nishantg7** [comment]
Apologies for raising an issue here but is there any solution you can provide on this case, it would be great help if you could tell me where to raise this issue

**Comment by brknsoul** [comment]
I have no idea what your problem is. Again, this isn't something I can help you with.
