### ISSUE TITLE
No such file or directory for GPU arch : gfx1103

### ISSUE THREAD

**Issue by SantaSpeen** [brknsoul/ROCmLibs#4]
**Describe the bug**
`rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1103`

**Comment by brknsoul** [comment]
These ROCmLibs are designed for HIP SDK 5.7.1.
